# Generated by Django 4.2.16 on 2025-06-15 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feira',
            name='preco_ingresso',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Preço do Ingresso'),
        ),
    ]
